import "package:flow/data/transaction_filter.dart";
import "package:flow/data/transactions_filter/time_range.dart";
import "package:flow/entity/account.dart";
import "package:flow/entity/category.dart";
import "package:flow/entity/transaction.dart";
import "package:flow/l10n/extensions.dart";
import "package:flow/l10n/named_enum.dart";
import "package:flow/objectbox.dart";
import "package:flow/services/accounts.dart";
import "package:flow/services/transactions.dart";
import "package:flow/sync/export/export_pdf/headers.dart";
import "package:flutter/services.dart";
import "package:moment_dart/moment_dart.dart";
import "package:pdf/pdf.dart";
import "package:pdf/widgets.dart" as pw;

Future<Uint8List> generatePDFContent({
  List<Account>? whitelistedAccounts,
  required TimeRange timeRange,
}) async {
  final List<Account> accounts = await AccountsService().getAll();
  final List<Category> categories =
      await ObjectBox().box<Category>().getAllAsync();

  final Map<String, String> accountNames = {
    for (final Account account in accounts) account.uuid: account.name,
  };

  final Map<String, String> categoryNames = {
    for (final Category category in categories) category.uuid: category.name,
  };

  final TransactionFilter filter = TransactionFilter(
    accounts: whitelistedAccounts?.map((account) => account.uuid).toList(),
    range: TransactionFilterTimeRange.fromTimeRange(timeRange),
  );

  final List<Transaction> transactions = await TransactionsService().findMany(
    filter,
  );

  final List<String?> resultingAccounts =
      transactions
          .map((transaction) => transaction.accountUuid)
          .toSet()
          .toList();

  pw.TableRow generateRow(Transaction transaction) {
    return pw.TableRow(
      children: [
        pw.Text(
          transaction.transactionDate.format(payload: "LLL", forceLocal: true),
        ),
        pw.Text(
          transaction.title ??
              (transaction.isTransfer
                  ? "transaction.transfer.fromToTitle".tr({
                    "from":
                        accountNames[transaction
                            .extensions
                            .transfer
                            ?.fromAccountUuid] ??
                        "~",
                    "to":
                        accountNames[transaction
                            .extensions
                            .transfer
                            ?.toAccountUuid] ??
                        "~",
                  })
                  : "transaction.fallbackTitle".tr()),
        ),
        pw.Text(transaction.money.formatMoney()),
        pw.Text(accountNames[transaction.accountUuid] ?? "~"),
        pw.Text(categoryNames[transaction.categoryUuid] ?? "~"),
        pw.Text(transaction.type.localizedName),
      ],
    );
  }

  final pw.Document pdf = pw.Document();

  final Uint8List logoBytes = await rootBundle
      .load("assets/images/4.0x/flow.png")
      .then((value) => value.buffer.asUint8List());

  pdf.addPage(
    pw.Page(
      build: (pw.Context context) {
        return pw.Column(
          children: [
            pw.Row(
              children: [
                pw.Image(pw.MemoryImage(logoBytes)),
                pw.Text("Flow"),
                pw.Text(
                  "This report was generated by Flow. This document is purely for personal use and is not a legal document in any way or form.",
                ),
              ],
            ),
            pw.Row(
              children: [
                pw.Text(
                  "Statement for: ${resultingAccounts.nonNulls.map((account) => accountNames[account] ?? "~").join(", ")}",
                ),
                pw.Text(timeRange.format(useRelative: false)),
              ],
            ),
            pw.Divider(),
            pw.Text("transactions.title".tr()),
            pw.SizedBox(height: 20),
            pw.Table(
              border: pw.TableBorder.all(),
              children: [
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey300),
                  children:
                      PDFHeader.values
                          .map((header) => pw.Text(header.localizedName))
                          .toList(),
                ),
                ...transactions.map(generateRow),
              ],
            ),
          ],
        );
      },
    ),
  );

  return await pdf.save();
}
